In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a2 = a[np.newaxis, :]

In [4]:
a2.shape

(1, 6)

In [5]:
a = np.array([1,2,3])

In [6]:
a


array([1, 2, 3])

In [7]:
a[0]

1

In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.twos(4)

AttributeError: module 'numpy' has no attribute 'twos'

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.empty(2)

array([0., 0.])

In [12]:
import pandas as pd

In [13]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [14]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [15]:
dates = pd.date_range("20130101", periods=6)

In [16]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [18]:
df

A         B         C         D
2013-01-01 -0.962788 -0.326363  1.439005  1.608008
2013-01-02 -1.037285 -0.690986  1.636438 -1.286195
2013-01-03  1.890598  1.259699 -1.077477 -2.036243
2013-01-04 -1.632442 -0.189926 -1.694411 -0.647304
2013-01-05 -0.717949  0.354829 -1.484573  0.043667
2013-01-06 -0.042801 -0.053538 -0.984059 -0.413823

In [19]:
df['A']

2013-01-01   -0.962788
2013-01-02   -1.037285
2013-01-03    1.890598
2013-01-04   -1.632442
2013-01-05   -0.717949
2013-01-06   -0.042801
Freq: D, Name: A, dtype: float64

In [20]:
df2 = pd.DataFrame(
   ...:     {
   ...:         "A": 1.0,
   ...:         "B": pd.Timestamp("20130102"),
   ...:         "C": pd.Series(1, index=list(range(4)), dtype="float32"),
   ...:         "D": np.array([3] * 4, dtype="int32"),
   ...:         "E": pd.Categorical(["test", "train", "test", "train"]),
   ...:         "F": "foo",
   ...:     }
   ...: )

In [21]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [23]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [24]:
df.head()

A         B         C         D
2013-01-01 -0.962788 -0.326363  1.439005  1.608008
2013-01-02 -1.037285 -0.690986  1.636438 -1.286195
2013-01-03  1.890598  1.259699 -1.077477 -2.036243
2013-01-04 -1.632442 -0.189926 -1.694411 -0.647304
2013-01-05 -0.717949  0.354829 -1.484573  0.043667

In [25]:
df.head(2)

A         B         C         D
2013-01-01 -0.962788 -0.326363  1.439005  1.608008
2013-01-02 -1.037285 -0.690986  1.636438 -1.286195

In [26]:
df.tail(2)

A         B         C         D
2013-01-05 -0.717949  0.354829 -1.484573  0.043667
2013-01-06 -0.042801 -0.053538 -0.984059 -0.413823

In [27]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [28]:
df.to_numpy()

array([[-0.96278791, -0.32636259,  1.43900534,  1.60800755],
       [-1.03728488, -0.69098623,  1.63643805, -1.28619537],
       [ 1.89059839,  1.25969863, -1.07747667, -2.03624321],
       [-1.63244201, -0.18992562, -1.6944115 , -0.64730373],
       [-0.71794944,  0.3548288 , -1.48457328,  0.04366666],
       [-0.0428009 , -0.05353848, -0.98405874, -0.41382316]])

In [29]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [30]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.962788   -1.037285    1.890598   -1.632442   -0.717949   -0.042801
B   -0.326363   -0.690986    1.259699   -0.189926    0.354829   -0.053538
C    1.439005    1.636438   -1.077477   -1.694411   -1.484573   -0.984059
D    1.608008   -1.286195   -2.036243   -0.647304    0.043667   -0.413823

In [31]:
df.loc[dates[0]]

A   -0.962788
B   -0.326363
C    1.439005
D    1.608008
Name: 2013-01-01 00:00:00, dtype: float64

In [32]:
df.loc[dates[3]]

A   -1.632442
B   -0.189926
C   -1.694411
D   -0.647304
Name: 2013-01-04 00:00:00, dtype: float64

In [35]:
df.iloc[3]

A   -1.632442
B   -0.189926
C   -1.694411
D   -0.647304
Name: 2013-01-04 00:00:00, dtype: float64

In [36]:
df.iloc[3:5, 0:2]

A         B
2013-01-04 -1.632442 -0.189926
2013-01-05 -0.717949  0.354829

In [37]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

In [38]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [39]:
df = pd.DataFrame({"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]})

In [42]:
df["grade"] = df["raw_grade"].astype("category")

In [43]:
df["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): ['a', 'b', 'e']

In [45]:
df["grade"] = df["grade"].cat.set_categories(
   .....:     ["very bad", "bad", "medium", "good", "very good"])

In [46]:
df["grade"]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: grade, dtype: category
Categories (5, object): ['very bad', 'bad', 'medium', 'good', 'very good']

In [47]:
df["grade"].cat.categories = ["very good", "good", "very bad"]

ValueError: new categories need to have the same number of items as the old categories!

In [48]:
df["grade"].cat.categories = ["very good", "good", "very bad"]

ValueError: new categories need to have the same number of items as the old categories!

In [49]:
df["grade"] = df["raw_grade"].astype("category")

In [50]:
df["grade"].cat.categories = ["very good", "good", "very bad"]

In [52]:
df["grade"] = df["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])

In [53]:
df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): ['very bad', 'bad', 'medium', 'good', 'very good']

In [54]:
df.sort_values(by="grade")

id raw_grade      grade
5   6         e   very bad
1   2         b       good
2   3         b       good
0   1         a  very good
3   4         a  very good
4   5         a  very good

In [55]:
df.sort_values(by="id")


id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [56]:
df.groupby("grade").size()

grade
very bad     1
bad          0
medium       0
good         2
very good    3
dtype: int64