In [12]:
import numpy as np
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

mlpc = MLPClassifier(max_iter=5000)
mlpc.fit(X, y)

mlpc.predict(X)

array([0, 1, 1, 0])

In [8]:
import numpy as np
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

mlpc = linear_model.LassoLars(alpha=.1, normalize=False)
mlpc.fit(X, y)

mlpc.predict(X)

array([0.5, 0.5, 0.5, 0.5])

In [9]:
import numpy as np
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

mlpc = linear_model.RidgeCV(alphas=np.logspace(-6, 6, 13))
mlpc.fit(X, y)

mlpc.predict(X)

array([0.5, 0.5, 0.5, 0.5])

In [10]:
import numpy as np
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

mlpc = linear_model.Lasso(alpha=0.1)
mlpc.fit(X, y)

mlpc.predict(X)

array([0.5, 0.5, 0.5, 0.5])

In [11]:
import numpy as np
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

mlpc = linear_model.BayesianRidge()
mlpc.fit(X, y)

mlpc.predict(X)

array([0.5, 0.5, 0.5, 0.5])

In [13]:
import numpy as np
from sklearn import linear_model, tree
from sklearn.neural_network import MLPClassifier

X = np.array([[0,0], [0,1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

mlpc = tree.DecisionTreeClassifier()
mlpc.fit(X, y)

mlpc.predict(X)

array([0, 1, 1, 0])

In [14]:
import time
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml